branches:
        only:
                - master
                - og
os:
        - linux
dist: trusty
sudo: required
language:
        - cpp
compiler:
        - gcc
addons:
        apt:
                sources:
                        - ubuntu-toolchain-r-test
                packages:
                        - gcc-5
                        - g++-5
                        - cmake
language: generic

install:
        - wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz -O cmake.tar.gz
        - tar xvf cmake.tar.gz
        - mv cmake-3.12.1-Linux-x86_64 cmake
script:
        - sudo ln -s /usr/bin/gcc-5 /usr/local/bin/gcc
        - sudo ln -s /usr/bin/g++-5 /usr/local/bin/g++
        - export CC=/usr/bin/gcc-5
        - export CXX=/usr/bin/g++-5
        - mkdir build
        - cd build
        - ../cmake/bin/cmake ..
        - make
        - cd bin 
        - ./graphit_test
        - cd ..
        - python python_tests/test.py
        - python python_tests/test_with_schedules.py



