branches:
        only:
                - master
                - og
os:
        - linux
matrix:
	fast_finish: true
	include:
		- os: linux
			addons:
				apt:
					sources:
						- ubuntu-toolchain-r-test
					packages:
						- g++-4.9
			env:
				- MATRIX_EVAL="CC=gcc-4.9 && CXX=g++-4.9"

before_install:
    - eval "${MATRIX_EVAL}"

language: generic

install:
        - wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz -O cmake.tar.gz
        - tar xvf cmake.tar.gz
        - mv cmake-3.12.1-Linux-x86_64 cmake
script:
        - mkdir build
        - cd build
        - ../cmake/bin/cmake ..
        - make
        - cd bin 
        - ./graphit_test
        - cd ..
        - python python_tests/test.py
        - python python_tests/test_with_schedules.py



