os:
        - linux

language: generic

install:
        - wget https://cmake.org/files/v3.12/cmake-3.12.1-Linux-x86_64.tar.gz -O cmake.tar.gz
        - tar xvf cmake.tar.gz
        - mv cmake-3.12.1-Linux-x86_64 cmake
script:
        - mkdir build
        - cd build
        - ../cmake/bin/cmake ..
        - make
        - cd bin 
        - ./graphit_test
        - cd ../../test/python
        - python test.py
        - python test_with_schedules.py



